// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Home$ReactHooksTemplate = require("./Home.bs.js");
var Board$ReactHooksTemplate = require("./Board.bs.js");
var Login$ReactHooksTemplate = require("./Login.bs.js");
var NotFound$ReactHooksTemplate = require("./NotFound.bs.js");
var Register$ReactHooksTemplate = require("./Register.bs.js");
var Dashboard$ReactHooksTemplate = require("./Dashboard.bs.js");

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  console.log(url[/* path */0]);
  var match = url[/* path */0];
  var exit = 0;
  if (match) {
    switch (match[0]) {
      case "board" : 
          var match$1 = match[1];
          if (match$1 && !match$1[1]) {
            return React.createElement(Board$ReactHooksTemplate.make, {
                        id: match$1[0]
                      });
          } else {
            exit = 1;
          }
          break;
      case "dashboard" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(Dashboard$ReactHooksTemplate.make, { });
          }
          break;
      case "login" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(Login$ReactHooksTemplate.make, { });
          }
          break;
      case "register" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(Register$ReactHooksTemplate.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    return React.createElement(Home$ReactHooksTemplate.make, { });
  }
  if (exit === 1) {
    return React.createElement(NotFound$ReactHooksTemplate.make, { });
  }
  
}

var make = App;

exports.make = make;
/* react Not a pure module */
