// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Card$ReactHooksTemplate = require("./Card.bs.js");
var Util$ReactHooksTemplate = require("./Util.bs.js");

function Cards(Props) {
  var cards = Props.cards;
  if (cards !== undefined) {
    return React.createElement("div", undefined, React.createElement("ul", undefined, $$Array.map((function (card) {
                          if (card !== undefined) {
                            var card$1 = Caml_option.valFromOption(card);
                            return React.createElement(Card$ReactHooksTemplate.make, {
                                        id: card$1.id,
                                        text: card$1.text,
                                        votes: card$1.votes,
                                        comments: card$1.comments,
                                        key: card$1.id
                                      });
                          } else {
                            return Util$ReactHooksTemplate.ste("");
                          }
                        }), cards)));
  } else {
    return Util$ReactHooksTemplate.ste("No cards");
  }
}

var make = Cards;

exports.make = make;
/* react Not a pure module */
