// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Util$ReactHooksTemplate = require("./Util.bs.js");

function $$Comment(Props) {
  var id = Props.id;
  var text = Props.text;
  var author = Props.author;
  return React.createElement("li", {
              key: id,
              id: id
            }, React.createElement("div", undefined, Util$ReactHooksTemplate.ste(text)), React.createElement("div", undefined, Util$ReactHooksTemplate.ste(author.firstName), Util$ReactHooksTemplate.ste(author.lastName)));
}

var make = $$Comment;

exports.make = make;
/* react Not a pure module */
