// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function ste(prim) {
  return prim;
}

function goTo($$event, route) {
  $$event.preventDefault();
  return ReasonReactRouter.push(route);
}

function Home(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Welcome to Ansarada's fun retro"), React.createElement("a", {
                  href: "/login",
                  onClick: (function (e) {
                      return goTo(e, "login");
                    })
                }, "Login"), React.createElement("br", undefined), React.createElement("span", undefined, "or"), React.createElement("br", undefined), React.createElement("a", {
                  href: "/register",
                  onClick: (function (e) {
                      return goTo(e, "register");
                    })
                }, "Create an account"));
}

var make = Home;

exports.ste = ste;
exports.goTo = goTo;
exports.make = make;
/* react Not a pure module */
