// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Util$ReactHooksTemplate = require("./Util.bs.js");

function InputField(Props) {
  var label = Props.label;
  var type_ = Props.type_;
  var onChange = Props.onChange;
  return React.createElement("div", undefined, React.createElement("label", undefined, Util$ReactHooksTemplate.ste(label)), React.createElement("input", {
                  placeholder: label,
                  type: type_,
                  onChange: onChange
                }));
}

var make = InputField;

exports.make = make;
/* react Not a pure module */
