// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var Util$ReactHooksTemplate = require("./Util.bs.js");

var ppx_printed_query = "mutation CreateBoard($name: String!, $maxVotes: Int!)  {\ncreateBoard(name: $name, maxVotes: $maxVotes)  {\nname  \nmaxVotes  \n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_dict.get(Caml_option.valFromOption(match), "createBoard");
    var tmp;
    if (match$1 !== undefined) {
      var value$1 = Caml_option.valFromOption(match$1);
      var match$2 = Js_json.decodeNull(value$1);
      if (match$2 !== undefined) {
        tmp = undefined;
      } else {
        var match$3 = Js_json.decodeObject(value$1);
        var tmp$1;
        if (match$3 !== undefined) {
          var value$2 = Caml_option.valFromOption(match$3);
          var match$4 = Js_dict.get(value$2, "name");
          var tmp$2;
          if (match$4 !== undefined) {
            var value$3 = Caml_option.valFromOption(match$4);
            var match$5 = Js_json.decodeString(value$3);
            tmp$2 = match$5 !== undefined ? match$5 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$3));
          } else {
            tmp$2 = Js_exn.raiseError("graphql_ppx: Field name on type Board is missing");
          }
          var match$6 = Js_dict.get(value$2, "maxVotes");
          var tmp$3;
          if (match$6 !== undefined) {
            var value$4 = Caml_option.valFromOption(match$6);
            var match$7 = Js_json.decodeNumber(value$4);
            tmp$3 = match$7 !== undefined ? match$7 | 0 : Js_exn.raiseError("graphql_ppx: Expected int, got " + JSON.stringify(value$4));
          } else {
            tmp$3 = Js_exn.raiseError("graphql_ppx: Field maxVotes on type Board is missing");
          }
          tmp$1 = {
            name: tmp$2,
            maxVotes: tmp$3
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = Caml_option.some(tmp$1);
      }
    } else {
      tmp = undefined;
    }
    return {
            createBoard: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(name, maxVotes, param) {
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "name",
                  name
                ],
                /* tuple */[
                  "maxVotes",
                  maxVotes
                ]
              ]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var name = variables.name;
  var maxVotes = variables.maxVotes;
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "name",
                  name
                ],
                /* tuple */[
                  "maxVotes",
                  maxVotes
                ]
              ]),
          parse: parse
        };
}

function ret_type(f) {
  return /* module */[];
}

var MT_Ret = /* module */[];

var CreateBoard = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var CreateBoardMutation = ReasonApollo.CreateMutation([
      ppx_printed_query,
      parse
    ]);

function NewBoard(Props) {
  var match = React.useReducer((function (state, action) {
          if (action.tag) {
            return /* record */[
                    /* name */state[/* name */0],
                    /* maxVotes */action[0]
                  ];
          } else {
            return /* record */[
                    /* name */action[0],
                    /* maxVotes */state[/* maxVotes */1]
                  ];
          }
        }), /* record */[
        /* name */"",
        /* maxVotes */"0"
      ]);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement(CreateBoardMutation[/* make */6], {
              children: (function (mutation, param) {
                  var tmp;
                  var tmp$1 = param[/* result */0];
                  tmp = typeof tmp$1 === "number" ? (
                      tmp$1 === 0 ? Util$ReactHooksTemplate.ste("Loading") : Util$ReactHooksTemplate.ste("")
                    ) : (
                      tmp$1.tag ? Util$ReactHooksTemplate.ste("Board created successfully") : Util$ReactHooksTemplate.ste("Error")
                    );
                  return React.createElement("div", undefined, React.createElement("span", undefined, tmp), React.createElement("form", {
                                  onSubmit: (function ($$event) {
                                      $$event.preventDefault();
                                      var createBoard = make(state[/* name */0], Caml_format.caml_int_of_string(state[/* maxVotes */1]), /* () */0);
                                      Curry._4(mutation, Caml_option.some(createBoard.variables), /* array */["getAllBoards"], undefined, /* () */0);
                                      return /* () */0;
                                    })
                                }, React.createElement("div", undefined, React.createElement("label", undefined, Util$ReactHooksTemplate.ste("Name")), React.createElement("input", {
                                          placeholder: "Name",
                                          type: "text",
                                          onChange: (function (e) {
                                              return Curry._1(dispatch, /* Name */Block.__(0, [e.target.value]));
                                            })
                                        })), React.createElement("div", undefined, React.createElement("label", undefined, Util$ReactHooksTemplate.ste("Max votes")), React.createElement("input", {
                                          placeholder: "Max votes",
                                          type: "number",
                                          onChange: (function (e) {
                                              return Curry._1(dispatch, /* MaxVotes */Block.__(1, [e.target.value]));
                                            })
                                        })), React.createElement("div", undefined, Util$ReactHooksTemplate.ste(state[/* name */0])), React.createElement("div", undefined, Util$ReactHooksTemplate.ste(state[/* maxVotes */1])), React.createElement("button", {
                                      type: "submit"
                                    }, Util$ReactHooksTemplate.ste("Create board"))));
                })
            });
}

var make$1 = NewBoard;

exports.CreateBoard = CreateBoard;
exports.CreateBoardMutation = CreateBoardMutation;
exports.make = make$1;
/* CreateBoardMutation Not a pure module */
