// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var Util$ReactHooksTemplate = require("./Util.bs.js");

var ppx_printed_query = "mutation CreateSection($name: String!, $boardId: ID!)  {\ncreateSection(name: $name, boardId: $boardId)  {\nname  \n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_dict.get(Caml_option.valFromOption(match), "createSection");
    var tmp;
    if (match$1 !== undefined) {
      var value$1 = Caml_option.valFromOption(match$1);
      var match$2 = Js_json.decodeNull(value$1);
      if (match$2 !== undefined) {
        tmp = undefined;
      } else {
        var match$3 = Js_json.decodeObject(value$1);
        var tmp$1;
        if (match$3 !== undefined) {
          var match$4 = Js_dict.get(Caml_option.valFromOption(match$3), "name");
          var tmp$2;
          if (match$4 !== undefined) {
            var value$2 = Caml_option.valFromOption(match$4);
            var match$5 = Js_json.decodeString(value$2);
            tmp$2 = match$5 !== undefined ? match$5 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$2));
          } else {
            tmp$2 = Js_exn.raiseError("graphql_ppx: Field name on type Section is missing");
          }
          tmp$1 = {
            name: tmp$2
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = Caml_option.some(tmp$1);
      }
    } else {
      tmp = undefined;
    }
    return {
            createSection: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(name, boardId, param) {
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "name",
                  name
                ],
                /* tuple */[
                  "boardId",
                  boardId
                ]
              ]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var name = variables.name;
  var boardId = variables.boardId;
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "name",
                  name
                ],
                /* tuple */[
                  "boardId",
                  boardId
                ]
              ]),
          parse: parse
        };
}

function ret_type(f) {
  return /* module */[];
}

var MT_Ret = /* module */[];

var CreateSection = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var CreateSectionMutation = ReasonApollo.CreateMutation([
      ppx_printed_query,
      parse
    ]);

function NewSection(Props) {
  var boardId = Props.boardId;
  var match = React.useReducer((function (_state, action) {
          return /* record */[/* name */action[0]];
        }), /* record */[/* name */""]);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement(CreateSectionMutation[/* make */6], {
              children: (function (mutation, param) {
                  var tmp;
                  var tmp$1 = param[/* result */0];
                  tmp = typeof tmp$1 === "number" ? (
                      tmp$1 === 0 ? Util$ReactHooksTemplate.ste("Loading") : Util$ReactHooksTemplate.ste("")
                    ) : (
                      tmp$1.tag ? Util$ReactHooksTemplate.ste("Section created successfully") : Util$ReactHooksTemplate.ste("Error")
                    );
                  return React.createElement("div", undefined, React.createElement("span", undefined, tmp), React.createElement("form", {
                                  onSubmit: (function ($$event) {
                                      $$event.preventDefault();
                                      var createSection = make(state[/* name */0], boardId, /* () */0);
                                      Curry._4(mutation, Caml_option.some(createSection.variables), /* array */["board(id: $id)"], undefined, /* () */0);
                                      return /* () */0;
                                    })
                                }, React.createElement("div", undefined, React.createElement("label", undefined, Util$ReactHooksTemplate.ste("Name")), React.createElement("input", {
                                          placeholder: "Name",
                                          type: "text",
                                          value: state[/* name */0],
                                          onChange: (function (e) {
                                              return Curry._1(dispatch, /* Name */[e.target.value]);
                                            })
                                        })), React.createElement("button", {
                                      type: "submit"
                                    }, Util$ReactHooksTemplate.ste("Create section"))));
                })
            });
}

var make$1 = NewSection;

exports.CreateSection = CreateSection;
exports.CreateSectionMutation = CreateSectionMutation;
exports.make = make$1;
/* CreateSectionMutation Not a pure module */
