// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function NotFound(Props) {
  return React.createElement("h1", undefined, "Page not found");
}

var make = NotFound;

exports.make = make;
/* react Not a pure module */
