// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ste(prim) {
  return prim;
}

function Register(Props) {
  return React.createElement("h1", undefined, "Register");
}

var make = Register;

exports.ste = ste;
exports.make = make;
/* react Not a pure module */
