// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Util$ReactHooksTemplate = require("./Util.bs.js");
var Cards$ReactHooksTemplate = require("./Cards.bs.js");

function Sections(Props) {
  var sections = Props.sections;
  if (sections !== undefined) {
    return React.createElement("div", undefined, $$Array.map((function (section) {
                      if (section !== undefined) {
                        var section$1 = Caml_option.valFromOption(section);
                        return React.createElement("div", {
                                    key: section$1.id
                                  }, React.createElement("h2", undefined, Util$ReactHooksTemplate.ste(section$1.name)), React.createElement(Cards$ReactHooksTemplate.make, {
                                        cards: section$1.cards
                                      }));
                      } else {
                        return Util$ReactHooksTemplate.ste("");
                      }
                    }), sections));
  } else {
    return Util$ReactHooksTemplate.ste("No sections");
  }
}

var make = Sections;

exports.make = make;
/* react Not a pure module */
